name = "cloudflare-project-worker-graph"
main = "src/index.ts"
compatibility_date = "2024-08-20"

[dev]
port = 8787

# Environment variables for development
# Set these in production using: wrangler secret put OPENAI_API_KEY
# For development, you can also create a .dev.vars file
[[routes]]
pattern = "meadery.win/graph*"
zone_name = "meadery.win"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# Example .dev.vars file content (create this file and add your keys):
# OPENAI_API_KEY=your_openai_api_key_here
# DEEPSEEK_API_KEY=your_deepseek_api_key_here